'use client';

import { useMemo, useState } from 'react';
import { LocaleShell } from '@/components/LocaleShell';
import { JsonLd } from '@/components/JsonLd';
import { WhatsAppCTA } from '@/components/WhatsAppCTA';
import type { Locale } from '@/lib/i18n';
import type {
  PlannerPlan,
  PlannerResponseBody,
} from '@/lib/planner/types';

// ─── Copy per locale ─────────────────────────────────────────────────────────

type Copy = {
  eyebrow: string;
  h1: string;
  intro: string;
  trustChip: string;
  trustSentence: string;
  form: {
    days: string;
    travelers: string;
    budget: string;
    budgetOptions: [string, string, string, string]; // backpacker, mid, boutique, luxury
    pace: string;
    paceOptions: [string, string, string];
    interests: string;
    interestOptions: string[];
    style: string;
    freeform: string;
    freeformPlaceholder: string;
    submit: string;
    submitting: string;
    error: string;
  };
  cards: {
    aboutMe: string;
    brief: string;
    days: string;
    stays: string;
    budget: string;
    tips: string;
    when: string;
    nextStep: string;
    print: string;
    reset: string;
  };
  poweredBy: string;
  disclaimer: string;
};

const COPY: Record<Locale, Copy> = {
  en: {
    eyebrow: 'AI Travel Planner · Built by Moroccans',
    h1: 'Plan your Morocco trip with the first AI trained by local experts',
    intro:
      'Our AI planner was built from scratch by a team of Moroccan developers in Casablanca and trained on hyper-accurate, insider knowledge about every corner of the country. Real prices, real drive times, real riads — not generic advice.',
    trustChip: '🇲🇦 Built in Casablanca',
    trustSentence:
      'More reliable than any generic AI on the market because we trained it on the streets we actually walk.',
    form: {
      days: 'Trip length (days)',
      travelers: 'Travellers',
      budget: 'Budget tier',
      budgetOptions: ['Backpacker', 'Mid-range', 'Boutique', 'Luxury'],
      pace: 'Pace',
      paceOptions: ['Relaxed', 'Balanced', 'Packed'],
      interests: 'Interests',
      interestOptions: [
        'Culture & history',
        'Food & souks',
        'Sahara & camels',
        'Atlas & hiking',
        'Beaches & surf',
        'Photography',
        'Wellness & hammam',
        'Family-friendly',
      ],
      style: 'Anything specific? (optional)',
      freeform: 'Anything else we should know',
      freeformPlaceholder:
        'e.g. arriving from Dubai on 3 Oct, honeymoon, no early mornings, prefer riads with pools…',
      submit: 'Generate my plan',
      submitting: 'The planner is thinking…',
      error: 'Something went wrong. Please try again.',
    },
    cards: {
      aboutMe: 'About your planner',
      brief: 'Trip in one line',
      days: 'Day-by-day',
      stays: 'Where to stay',
      budget: 'Estimated budget',
      tips: 'Insider tips',
      when: 'Best time',
      nextStep: 'Next step',
      print: 'Save as PDF',
      reset: 'Start over',
    },
    poweredBy: 'Powered by MoroccoForYou · Built by Moroccan developers in Casablanca',
    disclaimer:
      'Plan is generated by our AI. Bookings, availability, and final prices are confirmed by a human on WhatsApp before you pay anything.',
  },
  fr: {
    eyebrow: 'Planificateur IA · Conçu par des Marocains',
    h1: 'Planifiez votre voyage au Maroc avec la première IA entraînée par des experts locaux',
    intro:
      'Notre planificateur a été construit de zéro par une équipe de développeurs marocains à Casablanca, et entraîné avec un savoir local hyper-précis sur chaque coin du pays. Vrais prix, vraies durées de trajet, vrais riads — pas de conseils génériques.',
    trustChip: '🇲🇦 Fait à Casablanca',
    trustSentence:
      'Plus fiable qu’aucune IA générique parce que nous l’avons entraînée dans les rues où nous marchons vraiment.',
    form: {
      days: 'Durée du voyage (jours)',
      travelers: 'Voyageurs',
      budget: 'Budget',
      budgetOptions: ['Sac à dos', 'Milieu de gamme', 'Boutique', 'Luxe'],
      pace: 'Rythme',
      paceOptions: ['Tranquille', 'Équilibré', 'Intense'],
      interests: 'Centres d’intérêt',
      interestOptions: [
        'Culture & histoire',
        'Gastronomie & souks',
        'Sahara & dromadaires',
        'Atlas & randonnée',
        'Plages & surf',
        'Photographie',
        'Bien-être & hammam',
        'En famille',
      ],
      style: 'Précisions (optionnel)',
      freeform: 'Autre chose à savoir',
      freeformPlaceholder:
        'ex. arrivée de Paris le 3 oct, voyage de noces, pas de réveils tôt, riads avec piscine…',
      submit: 'Générer mon plan',
      submitting: 'Le planificateur réfléchit…',
      error: 'Une erreur est survenue. Réessayez.',
    },
    cards: {
      aboutMe: 'Votre planificateur',
      brief: 'Votre voyage en une ligne',
      days: 'Jour par jour',
      stays: 'Où dormir',
      budget: 'Budget estimé',
      tips: 'Conseils d’initié',
      when: 'Meilleure saison',
      nextStep: 'Prochaine étape',
      print: 'Enregistrer en PDF',
      reset: 'Recommencer',
    },
    poweredBy: 'Propulsé par MoroccoForYou · Conçu par des développeurs marocains à Casablanca',
    disclaimer:
      'Plan généré par notre IA. Réservations, disponibilités et prix finaux sont confirmés par un humain sur WhatsApp avant tout paiement.',
  },
  ar: {
    eyebrow: 'مخطط ذكي · صناعة مغربية',
    h1: 'خطط لرحلتك إلى المغرب مع أول ذكاء اصطناعي درّبه خبراء محليون',
    intro:
      'مخططنا الذكي بُني من الصفر على يد فريق من المطورين المغاربة في الدار البيضاء، ودُرّب على معرفة محلية دقيقة عن كل ركن من أركان البلاد. أسعار حقيقية، أوقات سفر حقيقية، رياضات حقيقية — لا نصائح عامة.',
    trustChip: '🇲🇦 صُنع في الدار البيضاء',
    trustSentence: 'أكثر موثوقية من أي ذكاء اصطناعي عام، لأننا درّبناه في الأزقة التي نمشيها فعلًا.',
    form: {
      days: 'مدة الرحلة (أيام)',
      travelers: 'عدد المسافرين',
      budget: 'مستوى الميزانية',
      budgetOptions: ['اقتصادي', 'متوسط', 'بوتيك', 'فاخر'],
      pace: 'الإيقاع',
      paceOptions: ['هادئ', 'متوازن', 'مكثف'],
      interests: 'الاهتمامات',
      interestOptions: [
        'الثقافة والتاريخ',
        'الطعام والأسواق',
        'الصحراء والجمال',
        'الأطلس والمشي',
        'الشواطئ والسرف',
        'التصوير',
        'العافية والحمام',
        'مناسب للعائلات',
      ],
      style: 'تفاصيل إضافية (اختياري)',
      freeform: 'أي شيء آخر نحتاج معرفته',
      freeformPlaceholder:
        'مثال: قادم من دبي في 3 أكتوبر، شهر عسل، لا استيقاظ مبكرًا، نفضل رياضات بمسبح…',
      submit: 'أنشئ خطتي',
      submitting: 'المخطط يفكر…',
      error: 'حدث خطأ. حاول مرة أخرى.',
    },
    cards: {
      aboutMe: 'عن مخططك',
      brief: 'رحلتك في سطر',
      days: 'يومًا بيوم',
      stays: 'أين تقيم',
      budget: 'الميزانية التقديرية',
      tips: 'نصائح من الداخل',
      when: 'أفضل موسم',
      nextStep: 'الخطوة التالية',
      print: 'حفظ PDF',
      reset: 'إعادة البدء',
    },
    poweredBy: 'مدعوم من MoroccoForYou · بناها مطورون مغاربة في الدار البيضاء',
    disclaimer:
      'الخطة يولّدها الذكاء الاصطناعي. الحجوزات والتوفر والأسعار النهائية يؤكدها إنسان عبر واتساب قبل أي دفع.',
  },
};

// ─── Component ───────────────────────────────────────────────────────────────

const API_URL = process.env.NEXT_PUBLIC_AI_API_URL || '/api/planner';

export function AIPlannerView({ locale }: { locale: Locale }) {
  const t = COPY[locale];
  const [days, setDays] = useState(7);
  const [travelers, setTravelers] = useState(2);
  const [budgetIdx, setBudgetIdx] = useState(1);
  const [paceIdx, setPaceIdx] = useState(1);
  const [interests, setInterests] = useState<string[]>([t.form.interestOptions[0], t.form.interestOptions[2]]);
  const [freeform, setFreeform] = useState('');
  const [state, setState] = useState<
    | { status: 'idle' }
    | { status: 'loading' }
    | { status: 'ok'; plan: PlannerPlan; raw: string }
    | { status: 'error'; message: string }
  >({ status: 'idle' });

  function toggleInterest(v: string) {
    setInterests((prev) => (prev.includes(v) ? prev.filter((x) => x !== v) : [...prev, v]));
  }

  const composedPrompt = useMemo(
    () =>
      [
        `Plan a Morocco trip in ${locale} language.`,
        `Length: ${days} days.`,
        `Travellers: ${travelers}.`,
        `Budget tier: ${t.form.budgetOptions[budgetIdx]}.`,
        `Pace: ${t.form.paceOptions[paceIdx]}.`,
        `Interests: ${interests.join(', ') || 'general sightseeing'}.`,
        freeform.trim() ? `Additional: ${freeform.trim()}` : '',
      ]
        .filter(Boolean)
        .join('\n'),
    [locale, days, travelers, budgetIdx, paceIdx, interests, freeform, t],
  );

  async function generate() {
    setState({ status: 'loading' });
    try {
      const res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: composedPrompt, mode: 'plan', locale }),
      });
      const data = (await res.json()) as PlannerResponseBody;
      if (!data.ok) {
        setState({ status: 'error', message: data.error || t.form.error });
        return;
      }
      if (!data.plan) {
        // Fell back to unstructured reply — surface it as an error rather than
        // trying to render half a card grid.
        setState({ status: 'error', message: t.form.error });
        return;
      }
      setState({ status: 'ok', plan: data.plan, raw: data.reply });
    } catch (err) {
      setState({
        status: 'error',
        message: err instanceof Error ? err.message : t.form.error,
      });
    }
  }

  const showResult = state.status === 'ok';

  return (
    <LocaleShell locale={locale}>
      <JsonLd
        id="ld-planner-service"
        data={{
          '@context': 'https://schema.org',
          '@type': 'Service',
          '@id': 'https://www.moroccoforyou.com/planner/#service',
          name: 'MoroccoForYou AI Travel Planner',
          serviceType: 'AI-powered Morocco travel itinerary planning',
          description: t.intro,
          provider: {
            '@type': 'TravelAgency',
            name: 'MoroccoForYou',
            areaServed: { '@type': 'Country', name: 'Morocco' },
            address: {
              '@type': 'PostalAddress',
              addressLocality: 'Casablanca',
              addressCountry: 'MA',
            },
          },
          areaServed: { '@type': 'Country', name: 'Morocco' },
          availableLanguage: ['en', 'fr', 'ar'],
        }}
      />

      {/* ── Hero ───────────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden bg-gradient-to-br from-brand-night via-brand-night to-[#1a2b47] text-brand-cream print:hidden">
        <div className="mx-auto grid max-w-6xl gap-8 px-4 py-14 md:grid-cols-[1fr_auto] md:items-end md:py-20">
          <div>
            <p className="inline-flex items-center gap-2 rounded-full bg-brand-terracotta/20 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-brand-terracotta">
              <span aria-hidden>✦</span> {t.eyebrow}
            </p>
            <h1 className="mt-4 font-display text-3xl font-bold leading-tight md:text-5xl">
              {t.h1}
            </h1>
            <p className="mt-4 max-w-2xl text-brand-cream/85">{t.intro}</p>
            <p className="mt-3 max-w-2xl text-sm text-brand-cream/70 italic">{t.trustSentence}</p>
          </div>
          <div className="flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 text-sm backdrop-blur">
            <span aria-hidden>🇲🇦</span>
            <span>{t.trustChip}</span>
          </div>
        </div>
      </section>

      {/* ── Form ──────────────────────────────────────────────────────── */}
      {!showResult && (
        <section className="mx-auto max-w-4xl px-4 py-10 print:hidden">
          <div className="rounded-3xl border border-brand-night/10 bg-white p-6 shadow-sm md:p-10">
            <div className="grid gap-6 md:grid-cols-2">
              <div>
                <label className="block text-sm font-semibold text-brand-night">
                  {t.form.days}
                </label>
                <input
                  type="range"
                  min={3}
                  max={21}
                  value={days}
                  onChange={(e) => setDays(Number(e.target.value))}
                  className="mt-2 w-full accent-brand-terracotta"
                />
                <p className="mt-1 text-sm text-brand-night/70">
                  {days} {locale === 'ar' ? 'أيام' : locale === 'fr' ? 'jours' : 'days'}
                </p>
              </div>
              <div>
                <label className="block text-sm font-semibold text-brand-night">
                  {t.form.travelers}
                </label>
                <input
                  type="number"
                  min={1}
                  max={12}
                  value={travelers}
                  onChange={(e) =>
                    setTravelers(Math.max(1, Math.min(12, Number(e.target.value) || 1)))
                  }
                  className="mt-2 w-full rounded-lg border border-brand-night/20 bg-white px-3 py-2 text-brand-night focus:border-brand-terracotta focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-brand-night">
                  {t.form.budget}
                </label>
                <div className="mt-2 flex flex-wrap gap-2">
                  {t.form.budgetOptions.map((opt, i) => (
                    <button
                      key={opt}
                      type="button"
                      onClick={() => setBudgetIdx(i)}
                      className={`rounded-full border px-3 py-1.5 text-sm ${
                        budgetIdx === i
                          ? 'border-brand-terracotta bg-brand-terracotta text-white'
                          : 'border-brand-night/20 text-brand-night hover:border-brand-terracotta'
                      }`}
                    >
                      {opt}
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <label className="block text-sm font-semibold text-brand-night">
                  {t.form.pace}
                </label>
                <div className="mt-2 flex flex-wrap gap-2">
                  {t.form.paceOptions.map((opt, i) => (
                    <button
                      key={opt}
                      type="button"
                      onClick={() => setPaceIdx(i)}
                      className={`rounded-full border px-3 py-1.5 text-sm ${
                        paceIdx === i
                          ? 'border-brand-terracotta bg-brand-terracotta text-white'
                          : 'border-brand-night/20 text-brand-night hover:border-brand-terracotta'
                      }`}
                    >
                      {opt}
                    </button>
                  ))}
                </div>
              </div>
              <div className="md:col-span-2">
                <label className="block text-sm font-semibold text-brand-night">
                  {t.form.interests}
                </label>
                <div className="mt-2 flex flex-wrap gap-2">
                  {t.form.interestOptions.map((opt) => {
                    const active = interests.includes(opt);
                    return (
                      <button
                        key={opt}
                        type="button"
                        onClick={() => toggleInterest(opt)}
                        className={`rounded-full border px-3 py-1.5 text-sm transition ${
                          active
                            ? 'border-brand-oasis bg-brand-oasis text-white'
                            : 'border-brand-night/20 text-brand-night hover:border-brand-terracotta'
                        }`}
                      >
                        {opt}
                      </button>
                    );
                  })}
                </div>
              </div>
              <div className="md:col-span-2">
                <label className="block text-sm font-semibold text-brand-night">
                  {t.form.freeform}
                </label>
                <textarea
                  rows={3}
                  value={freeform}
                  onChange={(e) => setFreeform(e.target.value)}
                  placeholder={t.form.freeformPlaceholder}
                  className="mt-2 w-full rounded-xl border border-brand-night/20 bg-white px-3 py-2 text-brand-night placeholder:text-brand-night/40 focus:border-brand-terracotta focus:outline-none"
                />
              </div>
            </div>

            <div className="mt-8 flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:justify-between">
              <button
                type="button"
                onClick={generate}
                disabled={state.status === 'loading'}
                className="inline-flex items-center gap-2 rounded-full bg-brand-terracotta px-6 py-3 text-sm font-semibold text-white transition hover:bg-brand-night disabled:opacity-60"
              >
                <span aria-hidden>✦</span>
                {state.status === 'loading' ? t.form.submitting : t.form.submit}
              </button>
              <p className="text-xs text-brand-night/60">{t.poweredBy}</p>
            </div>

            {state.status === 'error' && (
              <p role="alert" className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-800">
                {state.message}
              </p>
            )}
          </div>
        </section>
      )}

      {/* ── Result cards ──────────────────────────────────────────────── */}
      {showResult && state.status === 'ok' && (
        <PlanCards
          plan={state.plan}
          copy={t}
          locale={locale}
          onReset={() => setState({ status: 'idle' })}
        />
      )}

      <p className="mx-auto max-w-4xl px-4 pb-16 text-center text-xs text-brand-night/50 print:hidden">
        {t.disclaimer}
      </p>
    </LocaleShell>
  );
}

// ─── Result grid ─────────────────────────────────────────────────────────────

function PlanCards({
  plan,
  copy,
  locale,
  onReset,
}: {
  plan: PlannerPlan;
  copy: Copy;
  locale: Locale;
  onReset: () => void;
}) {
  const t = copy;

  function printPlan() {
    if (typeof window !== 'undefined') window.print();
  }

  return (
    <section
      className="mx-auto max-w-6xl px-4 py-10 print:px-0 print:py-0"
      id="planner-result"
      aria-label="Your Morocco plan"
    >
      {/* Action bar (hidden on print) */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest text-brand-terracotta">
            {t.eyebrow}
          </p>
          <h2 className="mt-1 font-display text-2xl font-bold text-brand-night md:text-3xl">
            {plan.brief}
          </h2>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={printPlan}
            className="inline-flex items-center gap-2 rounded-full border border-brand-night/20 bg-white px-4 py-2 text-sm font-semibold text-brand-night hover:border-brand-terracotta"
          >
            <span aria-hidden>⬇</span> {t.cards.print}
          </button>
          <button
            type="button"
            onClick={onReset}
            className="inline-flex items-center gap-2 rounded-full border border-brand-night/20 bg-white px-4 py-2 text-sm font-semibold text-brand-night hover:border-brand-terracotta"
          >
            {t.cards.reset}
          </button>
        </div>
      </div>

      {/* Card grid */}
      <div className="grid gap-5 md:grid-cols-3">
        {/* Brief + About Me spans full width */}
        <Card className="md:col-span-3" tone="dark" title={t.cards.brief}>
          <p className="text-lg leading-relaxed text-brand-cream/95">{plan.brief}</p>
          <p className="mt-3 text-sm text-brand-cream/70 italic">
            <span className="font-semibold not-italic text-brand-terracotta">
              {t.cards.aboutMe}:
            </span>{' '}
            {plan.aboutMe}
          </p>
        </Card>

        {/* Days — 2/3 width on desktop */}
        <Card className="md:col-span-2" title={t.cards.days}>
          <ol className="space-y-4">
            {plan.days.map((d) => (
              <li key={d.day} className="rounded-xl bg-brand-cream/60 p-4">
                <p className="font-display text-lg font-semibold text-brand-night">
                  {d.title}
                </p>
                {d.drive && (
                  <p className="mt-1 text-xs uppercase tracking-wider text-brand-terracotta">
                    {d.drive}
                  </p>
                )}
                <ul className="mt-2 list-disc space-y-1 ps-5 text-sm text-brand-night/85">
                  {d.activities.map((a, i) => (
                    <li key={i}>{a}</li>
                  ))}
                </ul>
                {d.stayHint && (
                  <p className="mt-2 text-xs text-brand-night/60">🌙 {d.stayHint}</p>
                )}
              </li>
            ))}
          </ol>
        </Card>

        {/* Budget — sidebar */}
        <Card title={t.cards.budget} tone="accent">
          <p className="font-display text-3xl font-bold text-brand-night">
            {plan.budget.perPersonMin.toLocaleString()}
            <span className="mx-1 text-brand-night/50">–</span>
            {plan.budget.perPersonMax.toLocaleString()}{' '}
            <span className="text-lg font-medium text-brand-night/70">{plan.budget.currency}</span>
          </p>
          <p className="mt-2 text-sm text-brand-night/70">{plan.budget.notes}</p>
        </Card>

        {/* Stays */}
        <Card className="md:col-span-2" title={t.cards.stays}>
          <ul className="grid gap-3 sm:grid-cols-2">
            {plan.stays.map((s, i) => (
              <li
                key={i}
                className="rounded-xl border border-brand-night/10 bg-white p-4"
              >
                <p className="text-xs uppercase tracking-widest text-brand-terracotta">
                  {s.location}
                </p>
                <p className="mt-1 font-semibold text-brand-night">{s.name}</p>
                <p className="mt-1 text-xs text-brand-night/60">
                  {s.type} · {s.priceBand}
                </p>
                <p className="mt-2 text-sm text-brand-night/80">{s.why}</p>
              </li>
            ))}
          </ul>
        </Card>

        {/* Best time */}
        <Card title={t.cards.when}>
          <p className="text-sm leading-relaxed text-brand-night/85">{plan.bestTimeNotes}</p>
        </Card>

        {/* Tips */}
        <Card className="md:col-span-2" title={t.cards.tips}>
          <ul className="grid gap-2 sm:grid-cols-2">
            {plan.insiderTips.map((tip, i) => (
              <li
                key={i}
                className="flex gap-2 rounded-xl bg-brand-cream/60 p-3 text-sm text-brand-night/85"
              >
                <span aria-hidden className="text-brand-terracotta">
                  ★
                </span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </Card>

        {/* Next step */}
        <Card title={t.cards.nextStep} tone="accent">
          <p className="text-sm leading-relaxed text-brand-night/85">{plan.nextStep}</p>
          <div className="mt-4 print:hidden">
            <WhatsAppCTA
              message={`Hi MoroccoForYou! I just generated a Morocco plan with your AI planner (${plan.brief}). Can we lock the dates?`}
              label={locale === 'ar' ? 'تابع عبر واتساب' : locale === 'fr' ? 'Continuer sur WhatsApp' : 'Continue on WhatsApp'}
            />
          </div>
        </Card>
      </div>
    </section>
  );
}

function Card({
  title,
  children,
  className = '',
  tone = 'default',
}: {
  title: string;
  children: React.ReactNode;
  className?: string;
  tone?: 'default' | 'dark' | 'accent';
}) {
  const bg =
    tone === 'dark'
      ? 'bg-brand-night text-brand-cream'
      : tone === 'accent'
        ? 'bg-brand-sand/40'
        : 'bg-white';
  const border =
    tone === 'dark' ? 'border-brand-night' : 'border-brand-night/10';
  const titleColor =
    tone === 'dark' ? 'text-brand-terracotta' : 'text-brand-terracotta';
  return (
    <article
      className={`rounded-2xl border ${border} ${bg} p-5 shadow-sm ${className}`}
    >
      <h3
        className={`mb-3 text-xs font-semibold uppercase tracking-widest ${titleColor}`}
      >
        {title}
      </h3>
      {children}
    </article>
  );
}
