/**
 * Sample hotel data per destination. Replace with real partners.
 * Photos hotlink to Unsplash (free under their license).
 */

export type HotelType = 'riad' | 'boutique' | 'kasbah' | 'desert-camp' | 'resort' | 'guesthouse';

export type Hotel = {
  id: string;
  name: string;
  type: HotelType;
  location: string;
  rating: number;
  reviewCount: number;
  pricePerNightFromMAD: number;
  pricePerNightFromEUR: number;
  image: string;
  features: string[];
};

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=900&q=80&auto=format&fit=crop`;

const RIAD_1 = img('1582719508461-905c673771fd');
const RIAD_2 = img('1566073771259-6a8506099945');
const RIAD_3 = img('1551882547-ff40c63fe5fa');
const DESERT_CAMP = img('1547235001-d703406d3a89');
const KASBAH = img('1539635278303-d4002c07eae3');
const RESORT_POOL = img('1561501900-3701fa6a0864');
const BOUTIQUE = img('1551918120-9739cb430c6d');
const SEAFRONT = img('1518837695005-2083093ee35b');
const MOUNTAIN_LODGE = img('1545569341-9eb8b30979d9');

const HOTEL_TYPE_LABELS: Record<HotelType, string> = {
  riad: 'Riad',
  boutique: 'Boutique hotel',
  kasbah: 'Kasbah',
  'desert-camp': 'Desert camp',
  resort: 'Resort',
  guesthouse: 'Guesthouse',
};

export function hotelTypeLabel(type: HotelType): string {
  return HOTEL_TYPE_LABELS[type];
}

export const HOTELS_BY_DESTINATION: Record<string, Hotel[]> = {
  marrakech: [
    {
      id: 'riad-yasmine-mrk',
      name: 'Riad Yasmine',
      type: 'riad',
      location: 'Medina, near Jemaa el-Fnaa',
      rating: 4.9,
      reviewCount: 412,
      pricePerNightFromMAD: 1450,
      pricePerNightFromEUR: 132,
      image: RIAD_1,
      features: ['Plunge pool', 'Rooftop terrace', 'Hammam', 'Airport transfer'],
    },
    {
      id: 'la-mamounia-mrk',
      name: 'La Mamounia (Garden Wing)',
      type: 'resort',
      location: 'Hivernage',
      rating: 4.8,
      reviewCount: 1840,
      pricePerNightFromMAD: 8500,
      pricePerNightFromEUR: 775,
      image: RESORT_POOL,
      features: ['Iconic 1923 palace', 'Spa', 'Outdoor pool', 'Fine dining'],
    },
    {
      id: 'el-fenn-mrk',
      name: 'El Fenn',
      type: 'boutique',
      location: 'Medina, Bab el-Ksour',
      rating: 4.8,
      reviewCount: 980,
      pricePerNightFromMAD: 3200,
      pricePerNightFromEUR: 292,
      image: RIAD_3,
      features: ['Art-filled rooms', '3 pools', 'Rooftop bar', 'Adults-only'],
    },
  ],
  fes: [
    {
      id: 'palais-amani-fes',
      name: 'Palais Amani',
      type: 'riad',
      location: 'Fes el-Bali, near Bab Guissa',
      rating: 4.9,
      reviewCount: 612,
      pricePerNightFromMAD: 1850,
      pricePerNightFromEUR: 169,
      image: RIAD_2,
      features: ['Hammam', 'Cooking school', 'Garden courtyard', 'Free WiFi'],
    },
    {
      id: 'riad-fes-relais',
      name: 'Riad Fes — Relais & Châteaux',
      type: 'resort',
      location: 'Fes el-Bali',
      rating: 4.8,
      reviewCount: 920,
      pricePerNightFromMAD: 3400,
      pricePerNightFromEUR: 310,
      image: RIAD_3,
      features: ['Andalusian patio', 'Pool', 'Michelin-recommended restaurant'],
    },
    {
      id: 'dar-roumana-fes',
      name: 'Dar Roumana',
      type: 'guesthouse',
      location: 'North medina',
      rating: 4.7,
      reviewCount: 380,
      pricePerNightFromMAD: 980,
      pricePerNightFromEUR: 89,
      image: BOUTIQUE,
      features: ['Medina view', 'Breakfast included', 'Cooking classes'],
    },
  ],
  chefchaouen: [
    {
      id: 'lina-ryad-chef',
      name: 'Lina Ryad & Spa',
      type: 'riad',
      location: 'Medina, near Plaza Uta el-Hammam',
      rating: 4.7,
      reviewCount: 480,
      pricePerNightFromMAD: 950,
      pricePerNightFromEUR: 87,
      image: RIAD_1,
      features: ['Spa', 'Indoor pool', 'Rooftop terrace', 'Free parking'],
    },
    {
      id: 'dar-zambra-chef',
      name: 'Dar Zambra',
      type: 'guesthouse',
      location: 'Medina',
      rating: 4.8,
      reviewCount: 220,
      pricePerNightFromMAD: 620,
      pricePerNightFromEUR: 56,
      image: BOUTIQUE,
      features: ['Quiet alley', 'Excellent breakfast', 'Mountain views'],
    },
    {
      id: 'casa-perleta-chef',
      name: 'Casa Perleta',
      type: 'boutique',
      location: 'Upper medina',
      rating: 4.7,
      reviewCount: 310,
      pricePerNightFromMAD: 780,
      pricePerNightFromEUR: 71,
      image: RIAD_3,
      features: ['Family-run', 'Roof terrace', 'Walking distance to viewpoints'],
    },
  ],
  'sahara-merzouga': [
    {
      id: 'merzouga-luxury-camp',
      name: 'Merzouga Luxury Desert Camp',
      type: 'desert-camp',
      location: 'Erg Chebbi dunes',
      rating: 4.9,
      reviewCount: 540,
      pricePerNightFromMAD: 1650,
      pricePerNightFromEUR: 150,
      image: DESERT_CAMP,
      features: ['Private bathroom tents', 'Camel trek included', 'Berber music', '4WD transfer'],
    },
    {
      id: 'erg-chebbi-luxury-camp',
      name: 'Sahara Pearl Camp',
      type: 'desert-camp',
      location: 'East side of Erg Chebbi',
      rating: 4.8,
      reviewCount: 410,
      pricePerNightFromMAD: 1200,
      pricePerNightFromEUR: 109,
      image: DESERT_CAMP,
      features: ['Stargazing platform', 'Half-board', 'Sandboarding', 'Free transfer'],
    },
    {
      id: 'kasbah-mohayut',
      name: 'Kasbah Mohayut',
      type: 'kasbah',
      location: 'Edge of Erg Chebbi, Merzouga village',
      rating: 4.6,
      reviewCount: 720,
      pricePerNightFromMAD: 850,
      pricePerNightFromEUR: 77,
      image: KASBAH,
      features: ['Pool with dune view', 'Restaurant', 'Camel trek desk'],
    },
  ],
  casablanca: [
    {
      id: 'four-seasons-cas',
      name: 'Four Seasons Casablanca',
      type: 'resort',
      location: 'Corniche, Ain Diab',
      rating: 4.8,
      reviewCount: 1620,
      pricePerNightFromMAD: 4200,
      pricePerNightFromEUR: 383,
      image: RESORT_POOL,
      features: ['Ocean view', 'Spa', 'Beach access', '5 restaurants'],
    },
    {
      id: 'hotel-le-doge',
      name: 'Le Doge Hotel & Spa',
      type: 'boutique',
      location: 'Art Deco downtown',
      rating: 4.7,
      reviewCount: 540,
      pricePerNightFromMAD: 1850,
      pricePerNightFromEUR: 169,
      image: BOUTIQUE,
      features: ['Art Deco landmark', 'Spa', '8 themed suites'],
    },
    {
      id: 'movenpick-cas',
      name: 'Mövenpick Hotel Casablanca',
      type: 'resort',
      location: 'City center near Hassan II Mosque',
      rating: 4.5,
      reviewCount: 2100,
      pricePerNightFromMAD: 1450,
      pricePerNightFromEUR: 132,
      image: RIAD_3,
      features: ['Rooftop pool', 'Business center', 'Walk to mosque'],
    },
  ],
  essaouira: [
    {
      id: 'heure-bleue-ess',
      name: 'L’Heure Bleue Palais',
      type: 'resort',
      location: 'Medina, near Bab Sbaa',
      rating: 4.7,
      reviewCount: 720,
      pricePerNightFromMAD: 2400,
      pricePerNightFromEUR: 219,
      image: SEAFRONT,
      features: ['Rooftop pool', 'Spa', 'Ocean view', 'Cinema room'],
    },
    {
      id: 'riad-baoussala-ess',
      name: 'Riad Baoussala',
      type: 'riad',
      location: 'Outside the medina',
      rating: 4.8,
      reviewCount: 380,
      pricePerNightFromMAD: 980,
      pricePerNightFromEUR: 89,
      image: RIAD_2,
      features: ['Garden pool', 'Yoga deck', 'Free shuttle to beach'],
    },
    {
      id: 'salut-maroc-ess',
      name: 'Salut Maroc',
      type: 'boutique',
      location: 'Medina',
      rating: 4.7,
      reviewCount: 450,
      pricePerNightFromMAD: 720,
      pricePerNightFromEUR: 65,
      image: BOUTIQUE,
      features: ['Colorful rooms', 'Rooftop bar', 'Sea-facing'],
    },
  ],
  tangier: [
    {
      id: 'hotel-nord-pinus-tan',
      name: 'Hotel Nord-Pinus Tanger',
      type: 'boutique',
      location: 'Kasbah',
      rating: 4.7,
      reviewCount: 320,
      pricePerNightFromMAD: 2200,
      pricePerNightFromEUR: 200,
      image: BOUTIQUE,
      features: ['Strait of Gibraltar view', 'Antiques-filled', '5 suites'],
    },
    {
      id: 'el-minzah-tan',
      name: 'El Minzah Hotel',
      type: 'resort',
      location: 'Centre-ville',
      rating: 4.5,
      reviewCount: 1240,
      pricePerNightFromMAD: 1650,
      pricePerNightFromEUR: 150,
      image: RIAD_3,
      features: ['1930s landmark', 'Garden pool', 'Spa', 'Live piano bar'],
    },
    {
      id: 'dar-nour-tan',
      name: 'Dar Nour',
      type: 'guesthouse',
      location: 'Kasbah',
      rating: 4.8,
      reviewCount: 260,
      pricePerNightFromMAD: 850,
      pricePerNightFromEUR: 77,
      image: RIAD_1,
      features: ['Panoramic terrace', 'Family-run', 'Library lounge'],
    },
  ],
  rabat: [
    {
      id: 'la-tour-hassan-rab',
      name: 'La Tour Hassan Palace',
      type: 'resort',
      location: 'Centre-ville, near the Hassan Tower',
      rating: 4.6,
      reviewCount: 980,
      pricePerNightFromMAD: 1850,
      pricePerNightFromEUR: 169,
      image: RESORT_POOL,
      features: ['Andalusian architecture', 'Pool', 'Spa', 'Walking distance to monuments'],
    },
    {
      id: 'riad-kalaa-rab',
      name: 'Riad Kalaa',
      type: 'riad',
      location: 'Medina',
      rating: 4.7,
      reviewCount: 420,
      pricePerNightFromMAD: 920,
      pricePerNightFromEUR: 84,
      image: RIAD_2,
      features: ['Rooftop hammam', 'Garden', 'Cooking classes'],
    },
    {
      id: 'sofitel-jardin-rab',
      name: 'Sofitel Rabat Jardin des Roses',
      type: 'resort',
      location: 'Souissi',
      rating: 4.6,
      reviewCount: 1320,
      pricePerNightFromMAD: 2200,
      pricePerNightFromEUR: 200,
      image: RESORT_POOL,
      features: ['12 acres of gardens', 'Spa', 'Tennis courts', 'Family-friendly'],
    },
  ],
  agadir: [
    {
      id: 'riu-tikida-aga',
      name: 'Riu Tikida Beach',
      type: 'resort',
      location: 'Agadir beach',
      rating: 4.5,
      reviewCount: 3100,
      pricePerNightFromMAD: 1450,
      pricePerNightFromEUR: 132,
      image: RESORT_POOL,
      features: ['All-inclusive', 'Beachfront', '3 pools', 'Kids club'],
    },
    {
      id: 'sofitel-thalassa-aga',
      name: 'Sofitel Agadir Thalassa Sea & Spa',
      type: 'resort',
      location: 'Beachfront',
      rating: 4.7,
      reviewCount: 2240,
      pricePerNightFromMAD: 2400,
      pricePerNightFromEUR: 219,
      image: SEAFRONT,
      features: ['Thalassotherapy spa', 'Ocean view rooms', 'Adults pool'],
    },
    {
      id: 'paradis-plage-aga',
      name: 'Paradis Plage Surf Yoga & Spa',
      type: 'boutique',
      location: 'Taghazout, 25 min north',
      rating: 4.8,
      reviewCount: 540,
      pricePerNightFromMAD: 2100,
      pricePerNightFromEUR: 191,
      image: BOUTIQUE,
      features: ['Surf school', 'Yoga studio', 'Beachfront', 'Eco-design'],
    },
  ],
  'ait-ben-haddou': [
    {
      id: 'kasbah-ellouze-abh',
      name: 'Kasbah Ellouze',
      type: 'kasbah',
      location: 'Tamdaght, 15 min from the ksar',
      rating: 4.8,
      reviewCount: 320,
      pricePerNightFromMAD: 980,
      pricePerNightFromEUR: 89,
      image: KASBAH,
      features: ['Pool', 'Mountain view', 'Half-board', 'Cinema heritage'],
    },
    {
      id: 'dar-aicha-abh',
      name: 'Dar Aïcha',
      type: 'guesthouse',
      location: 'Foot of the ksar',
      rating: 4.7,
      reviewCount: 210,
      pricePerNightFromMAD: 480,
      pricePerNightFromEUR: 44,
      image: BOUTIQUE,
      features: ['Family-run', 'Rooftop dining', 'Walk to ksar'],
    },
    {
      id: 'la-rose-noire-abh',
      name: 'La Rose Noire',
      type: 'riad',
      location: 'Modern side of village',
      rating: 4.6,
      reviewCount: 260,
      pricePerNightFromMAD: 650,
      pricePerNightFromEUR: 59,
      image: RIAD_1,
      features: ['Terrace facing the ksar', 'Restaurant', 'Cooking demos'],
    },
  ],
  ouarzazate: [
    {
      id: 'le-berbere-palace-ouz',
      name: 'Le Berbère Palace',
      type: 'resort',
      location: 'City center',
      rating: 4.5,
      reviewCount: 920,
      pricePerNightFromMAD: 1450,
      pricePerNightFromEUR: 132,
      image: RESORT_POOL,
      features: ['Pool', 'Spa', 'Close to film studios'],
    },
    {
      id: 'kasbah-tigmi-ouz',
      name: 'Dar Daïf',
      type: 'kasbah',
      location: 'Outside Ouarzazate',
      rating: 4.8,
      reviewCount: 410,
      pricePerNightFromMAD: 720,
      pricePerNightFromEUR: 65,
      image: KASBAH,
      features: ['Traditional kasbah', 'Pool', 'Garden', 'Local cuisine'],
    },
    {
      id: 'riad-tigmi-ouz',
      name: 'Riad Tigmi du Soleil',
      type: 'riad',
      location: 'Skoura palmery, 40 min east',
      rating: 4.9,
      reviewCount: 280,
      pricePerNightFromMAD: 1850,
      pricePerNightFromEUR: 169,
      image: RIAD_2,
      features: ['In a palmery', 'Pool', 'Yoga deck', 'Half-board'],
    },
  ],
  'atlas-imlil': [
    {
      id: 'kasbah-toubkal-imlil',
      name: 'Kasbah du Toubkal',
      type: 'kasbah',
      location: 'Imlil',
      rating: 4.9,
      reviewCount: 420,
      pricePerNightFromMAD: 2400,
      pricePerNightFromEUR: 219,
      image: MOUNTAIN_LODGE,
      features: ['Berber hospitality project', 'Hammam', 'Mountain view', 'Half-board'],
    },
    {
      id: 'dar-imlil',
      name: 'Dar Imlil',
      type: 'guesthouse',
      location: 'Imlil village',
      rating: 4.7,
      reviewCount: 240,
      pricePerNightFromMAD: 580,
      pricePerNightFromEUR: 53,
      image: BOUTIQUE,
      features: ['Family-run', 'Hiking guide can be arranged', 'Half-board option'],
    },
    {
      id: 'douar-samra-imlil',
      name: 'Douar Samra',
      type: 'guesthouse',
      location: 'Above Imlil, in Tamatert',
      rating: 4.9,
      reviewCount: 180,
      pricePerNightFromMAD: 820,
      pricePerNightFromEUR: 75,
      image: MOUNTAIN_LODGE,
      features: ['Eco-retreat', 'No phone signal', 'Slow food', 'Walnut groves'],
    },
  ],
  dakhla: [
    {
      id: 'dakhla-attitude',
      name: 'Dakhla Attitude',
      type: 'resort',
      location: 'On the lagoon',
      rating: 4.7,
      reviewCount: 620,
      pricePerNightFromMAD: 1850,
      pricePerNightFromEUR: 169,
      image: SEAFRONT,
      features: ['Kitesurf school', 'Wing-foil lessons', 'Half-board', 'Lagoon view'],
    },
    {
      id: 'westpoint-dakhla',
      name: 'Westpoint Dakhla',
      type: 'resort',
      location: 'North end of the lagoon',
      rating: 4.8,
      reviewCount: 540,
      pricePerNightFromMAD: 2200,
      pricePerNightFromEUR: 200,
      image: SEAFRONT,
      features: ['Pro kite center', 'Bungalow rooms', 'All-inclusive', 'Pool'],
    },
    {
      id: 'casa-luna-dakhla',
      name: 'Casa Luna',
      type: 'boutique',
      location: 'Dakhla peninsula',
      rating: 4.6,
      reviewCount: 220,
      pricePerNightFromMAD: 1100,
      pricePerNightFromEUR: 100,
      image: BOUTIQUE,
      features: ['Adults-only', 'Yoga', 'Local seafood', 'Hammam'],
    },
  ],
};

export function getHotels(slug: string): Hotel[] {
  return HOTELS_BY_DESTINATION[slug] ?? [];
}
