// Side-effect imports. Each file registers its EN/FR/AR posts into
// BLOG_POSTS by calling `BLOG_POSTS.push(...)`. Importing this barrel from a
// page (or from `lib/blog.ts`) triggers registration once at module load.

import './01-how-many-days';
import './02-first-time-tips';
import './03-solo-female';
import './04-marrakech-street-food';
import './05-itinerary-10-days-budget';
import './06-best-beaches';
import './07-marrakech-to-chefchaouen';
import './08-dress-code';
import './09-fes-self-guided';
import './10-rent-a-car-tips';
import './11-driving-in-morocco';
import './12-morocco-2-weeks-itinerary';
import './13-things-to-do-morocco-7-days';
import './14-morocco-budget-backpacker';
import './15-best-time-sahara';
import './16-morocco-hammam';
import './17-rent-car-fes';
import './18-marrakech-fes-drive';
import './19-casablanca-airport-to-city';
import './20-casablanca-to-marrakech-by-car';
import './21-casablanca-nightlife';
import './22-best-car-rent-casablanca';
import './23-casablanca-agadir-by-car';
import './24-morocco-world-cup-2030-guide';
import './25-things-to-do-casablanca-one-day';
import './26-plan-morocco-trip-ai';
import './27-why-ai-morocco-travel-wrong';
import './28-best-car-morocco-ai-itinerary';
import './29-car-rental-casablanca-german-tourists';
import './30-casablanca-airport-car-rental';
import './31-morocco-cultural-rules-couples';
import './32-car-rental-casablanca-no-deposit';
import './33-how-to-get-from-casablanca-to-chefchaouen';
import './34-casablanca-to-rabat-by-car';
import './35-best-places-to-dine-in-casablanca';
import './36-casablanca-travel-guide';
import './37-chefchaouen-travel-guide';
import './38-casablanca-airport-guide-cmn';
import './39-marrakech-travel-guide';
import './40-fes-travel-guide';
import './41-sahara-desert-morocco-travel-guide';
import './42-agadir-travel-guide';
import './43-rabat-travel-guide';
import './44-the-odyssey-morocco-filming-locations';
import './45-essaouira-travel-guide';